version: 2.1
 
jobs:
  build:
    docker:
      - image: circleci/python:3.8
 
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Python dependencies
          command: |
            pip install pytest  
 
      # Run tests
      - run:
          name: Run tests
          command: |
            pytest test_sparse_recommender.py 

      # Start Docker daemon
      - setup_remote_docker:
          version: 19.03.13

      # Build Docker image upon successful tests
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/matrix-image:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
            docker push $DOCKERHUB_USERNAME/matrix-image:latest
 
workflows:
  version: 2
  test:
    jobs:
      - build
